project:
  type: book
  output-dir: docs
  resources:
    - "robots.txt"
    - "datasets"
    - "code"

strip-comments: true

crossref:
  fig-prefix: ""
  eq-prefix: ""
  sec-prefix: ""
  def-prefix: ""
  tbl-prefix: ""

number-depth: 2

callout-icon: false

date: last-modified
date-format: iso

book:
  date: last-modified
  date-format: iso
  # open-graph: true
  favicon: favicon.png
  cover-image: ada511logo8b.png
  title: "ADA511 [0.1]{.small .grey} <br>Data science and data-driven engineering"
  author:
    - Steffen Mæland
    - PierGianLuca Porta Mana
  # downloads: pdf
  reader-mode: true
  sidebar:
    date-format: iso
    date: last-modified
    title: "ADA511 [0.1]{.small .grey} <br>[updated {{< meta date >}}]{.small .grey}"
    logo: ada511logo8_small.png
    author:
      - name: Steffen Mæland
        orcid: 0000-0002-4652-4753
      - name: PierGianLuca  Porta Mana
        orcid: 0000-0002-6070-0784
    style: "docked"
    collapse-level: 4
  # search:
  #   location: navbar
  #   type: overlay
  chapters:
    - index.qmd
    - preface.qmd
    
    - part: "**An invitation**"
      chapters:
        - intro.qmd
        - framework.qmd
        - basic_decisions.qmd
    - connection-1-ML.qmd
    - part: "[**Inference I**]{.green}"
      chapters:
        - inference.qmd
        - sentences.qmd
        - truth_inference.qmd
        - probability_inference.qmd
        - derived_rules.qmd
        - monty.qmd
    - connection-2-ML.qmd
    - part: "[**Data I**]{.yellow}"

      chapters:
        - quantities_types.qmd
        - quantities_types_multi.qmd

    - part: "[**Inference II**]{.green}"
      chapters:
        - probability_distributions.qmd
        - joint_probability.qmd
        - marginal_probability.qmd
        - conditional_probability.qmd
        - information.qmd
    - connection-3-ML.qmd

    - part: "[**Data II**]{.yellow}"
      chapters:
        - populations_variates.qmd
        - statistics.qmd
        - subpopulations.qmd
        - samples.qmd

    - part: "[**Machine learning**]{.red}"
      chapters:
        - machine_learning_overview.qmd
        - decision_trees.qmd
        - neural_networks.qmd
    - beyond-ML.qmd
    - part: "[**Inference III**]{.green}"
      chapters:
        # - first_look_ML.qmd
        - exchangeable_probabilities.qmd
        - inference_from_freqs.qmd
        - inference_about_freqs.qmd
        - summary_formulae.qmd
    - part: "[**An Optimal Predictor Machine**]{.red}"
      chapters:
        - dirichlet-mixture.qmd
        - prototype_code.qmd
#        - OPM_application_nominal.qmd

    - part: "[**Decision theory**]{.lightblue}"
      chapters:
        - making_decisions.qmd
#   - missing_parts.qmd
#    - __old-connection-3-ML.qmd



bibliography: [portamanabib.bib, ADA511.bib]

format:
  html:
    # self-contained-math: true
    # embed-resources: true
    theme: flatly
    link-external-icon: false
    link-external-newwindow: true
    ## flatly journal litera simplex
    # mainfont: "DejaVu Sans"
    # monofont: "DejaVu Sans Mono"
    css: ada511styles.css
    html-math-method: mathjax
    reference-location: margin
    citation-location: margin
    toc-location: right
    toc-expand: true
    email-obfuscation: references
    # include-in-header: mathjax.html
    # sidebar:
    #   date-format: iso
    #   date: last-modified
    #   title: "ADA511 [0.1]{.small .grey} <br>Data science and data-driven engineering <br>updated {{< meta date >}}"

filters:
  - mathpunctuation.lua
#  - center-images.lua

  # pdf:
  #   keep-tex: true
  #   documentclass: scrreprt
  #   papersize: a4
  #   header-includes:
  #   - \usepackage{mathtools}
  #   - \usepackage[normalem]{ulem}

execute:
  freeze: auto
  # keep-ipynb: true


