project:
  type: book
  output-dir: docs

strip-comments: true

crossref:
  fig-prefix: ""
  eq-prefix: ""
  sec-prefix: ""
  def-prefix: ""
  tbl-prefix: ""

number-depth: 2

callout-icon: false

book:
  cover-image: ada511logo8.png
  title: "ADA511: <br>Data science and data-driven engineering"
  author:
    - Steffen Mæland
    - PierGianLuca Porta Mana
  # downloads: pdf
  reader-mode: true
  sidebar:
    title: "ADA511: <br>Data science and data-driven engineering"
    logo: ada511logo8_small.png
    date: last-modified
    author:
      - name: Steffen Mæland
        orcid: 0000-0002-4652-4753
      - name: PierGianLuca  Porta Mana
        orcid: 0000-0002-6070-0784
    style: "docked"
    collapse-level: 4
  date: last-modified
  date-format: iso
  chapters:
    - index.qmd
    
    - part: "An invitation"
      chapters:
        - intro.qmd
        - framework.qmd
        - basic_decisions.qmd
        
    - part: "Inference -- I"
      chapters:
        - inference.qmd
        - sentences.qmd
        - truth_inference.qmd
        - probability_inference.qmd
    - part: "Data -- I"
      chapters:
        - quantities_types.qmd
        - data_types_multi.qmd

    - part: "Inference -- II"
      chapters:
        - probability_distributions.qmd
        - joint_probability.qmd
        - marginal_conditional_probability.qmd
        
    - part: "Data -- II"
      chapters:
        - populations_variates.qmd
        - statistics.qmd
        - subpopulations.qmd
        
    - part: "Population inference"
      chapters:
        - exchangeability.qmd
        - populations_exchangeability.qmd
        
    - part: "Decision theory"
      chapters:
        - making_decisions.qmd

bibliography: [portamanabib.bib, ADA511.bib]

format:
  html:
    theme: flatly
    ## flatly journal litera simplex
    # mainfont: "IBM Plex Sans"
    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,700;1,400;1,700&family=IBM+Plex+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    mainfont: "IBM Plex Sans"
    monofont: "IBM Plex Mono"
    css: ada511styles.css
    html-math-method: mathjax
    reference-location: margin
    citation-location: margin
    toc-location: right
    toc-expand: true
    email-obfuscation: references
    # include-in-header: mathjax.html

filters:
  - mathpunctuation.lua

  # pdf:
  #   keep-tex: true
  #   documentclass: scrreprt
  #   papersize: a4
  #   header-includes:
  #   - \usepackage{mathtools}
  #   - \usepackage[normalem]{ulem}



