project:
  type: book
  output-dir: docs

crossref:
  fig-prefix: ""
  eq-prefix: ""
  sec-prefix: ""

number-depth: 2

callout-icon: false

book:
  cover-image: ada511logo8.png
  title: "ADA511: <br>Data science and data-driven engineering"
  author:
    - Steffen Mæland
    - PierGianLuca Porta Mana
  downloads: pdf
  reader-mode: true
  sidebar:
    title: "ADA511: <br>Data science and data-driven engineering"
    logo: ada511logo8_small.png
    date: last-modified
    author:
      - name: Steffen Mæland
        orcid: 0000-0002-4652-4753
      - name: PierGianLuca  Porta Mana
        orcid: 0000-0002-6070-0784
    style: "docked"
    collapse-level: 4
  date: last-modified
  date-format: iso
  chapters:
    - index.qmd
    - part: "An invitation"
      chapters:
        - intro.qmd
        - framework.qmd
        - basic_decisions.qmd
    - part: "Inference"
      chapters:
        - inference.qmd
        - sentences.qmd
        - truth_inference.qmd
        - probability_inference.qmd
        - probability_distributions.qmd
        - inference_exchangeability.qmd
    - part: "Information and data"
      chapters:
        - data_information.qmd
        - statistics.qmd
    - part: "Decision theory"
      chapters:
        - making_decisions.qmd

bibliography: [portamanabib.bib, ADA511.bib]

format:
  html:
    theme: flatly
    ## flatly journal litera simplex
    css: ada511styles.css
    html-math-method: mathjax
    reference-location: margin
    citation-location: margin
    toc-location: left
    toc-expand: true

  pdf:
    keep-tex: true
    documentclass: scrreprt
    papersize: a4
    header-includes:
    - \usepackage{mathtools}
    - \usepackage[normalem]{ulem}



