project:
  type: book
  output-dir: docs
  resources:
    - "robots.txt"
    - "datasets"
    - "code"

strip-comments: true

crossref:
  fig-prefix: ""
  eq-prefix: ""
  sec-prefix: ""
  def-prefix: ""
  tbl-prefix: ""

number-depth: 2

callout-icon: false

book:
  # open-graph: true
  favicon: ada511logo8_small.png
  cover-image: ada511logo8b.png
  title: "ADA511 [0.1]{.small .grey} <br>Data science and data-driven engineering"
  author:
    - Steffen Mæland
    - PierGianLuca Porta Mana
  # downloads: pdf
  reader-mode: true
  sidebar:
    title: "ADA511 [0.1]{.small .grey} <br>Data science and data-driven engineering"
    logo: ada511logo8_small.png
    date-format: iso
    date: last-modified
    author:
      - name: Steffen Mæland
        orcid: 0000-0002-4652-4753
      - name: PierGianLuca  Porta Mana
        orcid: 0000-0002-6070-0784
    style: "docked"
    collapse-level: 4
  # search:
  #   location: navbar
  #   type: overlay
  date: last-modified
  date-format: iso
  chapters:
    - index.qmd
    - preface.qmd
    
    - part: "**An invitation**"
      chapters:
        - intro.qmd
        - framework.qmd
        - basic_decisions.qmd
    - 0th_connection_ML.qmd
    - part: "[**Inference I**]{.green}"
      chapters:
        - inference.qmd
        - sentences.qmd
        - truth_inference.qmd
        - probability_inference.qmd
        - derived_rules.qmd
    - 1st_connection_ML.qmd
    - part: "[**Data I**]{.yellow}"
      
      chapters:
        - quantities_types.qmd
        - quantities_types_multi.qmd

    - part: "[**Inference II**]{.green}"
      chapters:
        - probability_distributions.qmd
        - joint_probability.qmd
        - marginal_conditional_probability.qmd
    - 2nd_connection_ML.qmd
        
    - part: "[**Data II**]{.yellow}"
      chapters:
        - populations_variates.qmd
        - statistics.qmd
        - subpopulations.qmd
        - samples.qmd

    - part: "[**Population inference**]{.green}"
      chapters:
        # - first_look_ML.qmd
        - recap.qmd
        - population_inference.qmd
        - exchangeability.qmd
        - inference_exchangeability.qmd
        - missing_parts.qmd
        - glass_application_R.qmd
        
    - part: "[**Decision theory**]{.lightblue}"
      chapters:
        - making_decisions.qmd
    
    - part: "[**Machine learning**]{.red}"
      chapters: 
        - machine_learning_overview.qmd
        - decision_trees.qmd
        - neural_networks.qmd

bibliography: [portamanabib.bib, ADA511.bib]

format:
  html:
    theme: flatly
    link-external-icon: false
    link-external-newwindow: true
    ## flatly journal litera simplex
    mainfont: "DejaVu Sans"
    monofont: "DejaVu Sans Mono"
    css: ada511styles.css
    html-math-method: mathjax
    reference-location: margin
    citation-location: margin
    toc-location: right
    toc-expand: true
    email-obfuscation: references
    # include-in-header: mathjax.html

filters:
  - mathpunctuation.lua

  # pdf:
  #   keep-tex: true
  #   documentclass: scrreprt
  #   papersize: a4
  #   header-includes:
  #   - \usepackage{mathtools}
  #   - \usepackage[normalem]{ulem}

execute:
  freeze: auto
  # keep-ipynb: true


